### ISSUE TITLE
краш по возвращении в главное меню стрелочкой <- после многократного свайпа.

### ISSUE THREAD

**Issue by userow** [IngvarJackal/FurView2#77]
**Реальное Устройство**: Sams Galaxy Grand 2 SM-G7102, ver 4.4.2, API 19

1) на главной Activity ввести в поиск текст (например "snow leopard")
2) дождаться загрузки
3) зайти в картинку
4) просвайпать вправо несколько раз (Хотя бы 1 раз, даже с 1й картинки)
5) нажать на кнопку <-

ER - возврат на главный экран
AR - краш

08-04 18:11:48.606  14820-14820/ru.furry.furview2 E/furry error﹕ java.lang.NullPointerException
            at ru.furry.furview2.MainActivity.onCreate(MainActivity.java:298)
            at android.app.Activity.performCreate(Activity.java:5541)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
08-04 18:11:48.606  14820-14820/ru.furry.furview2 D/AndroidRuntime﹕ Shutting down VM
08-04 18:11:48.606  14820-14820/ru.furry.furview2 W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x419d3da0)
08-04 18:11:48.606  14820-14820/ru.furry.furview2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ru.furry.furview2, PID: 14820
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.furry.furview2/ru.furry.furview2.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at ru.furry.furview2.MainActivity.onCreate(MainActivity.java:302)
            at android.app.Activity.performCreate(Activity.java:5541)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by IngvarJackal** [comment]
не воспроизводится. вероятно, ошибка блокирования ui. ждём мержа пулрквеста с ui #75 чтобы проверить ещё раз

**Comment by userow** [comment]
попробую на симе воссоздать.
на девайсе репродьюсится 3 раза из 3х

**Comment by IngvarJackal** [comment]
@userow см. #81 как нужно реализовывать воспроизводимость чтобы понятно было :)

**Comment by userow** [comment]
как вижу - исправлено убиранием кнопки.

**Comment by IngvarJackal** [comment]
Нет кнопки -- нет проблем :)

**Comment by IngvarJackal** [comment]
@userow кому эта кнопка вообще нужна?
