### ISSUE TITLE
Падение при нажатии кнопки поиска на главном экране

### ISSUE THREAD

**Issue by connertech** [IngvarJackal/FurView2#89]
Samsung GT-I9500, Android 5.0.1
ветка dev, версия 57ab2a7ace3ad1a97d0f54bbc33a2ade7c210aa7
1) Запустить приложение
2) Нажать кнопку поиска
Cразу после этого приложение падает.
Примечание: в поле для поиска может быть введен любой текст, на факт падения это не влияет.

Полный лог (момент нажатия виден по таймштампам):

```
08-07 22:37:14.747  30035-30035/? E/Zygote﹕ MountEmulatedStorage()
08-07 22:37:14.747  30035-30035/? E/Zygote﹕ v2
08-07 22:37:14.747  30035-30035/? I/libpersona﹕ KNOX_SDCARD checking this for 10332
08-07 22:37:14.747  30035-30035/? I/libpersona﹕ KNOX_SDCARD not a persona
08-07 22:37:14.752  30035-30035/? I/SELinux﹕ Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_GT-I9500_5.0.1 ver=27
08-07 22:37:14.757  30035-30035/? I/SELinux﹕ Function: selinux_compare_spd_ram , priority [1] , priority version is VE=SEPF_GT-I9500_5.0.1_0027
08-07 22:37:14.757  30035-30035/? E/SELinux﹕ [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
08-07 22:37:14.757  30035-30035/? I/art﹕ Late-enabling -Xcheck:jni
08-07 22:37:14.882  30035-30035/ru.furry.furview2 D/ResourcesManager﹕ creating new AssetManager and set to /data/app/ru.furry.furview2-2/base.apk
08-07 22:37:15.037  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
08-07 22:37:15.057  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-hdpi-v4/fl320.png
08-07 22:37:15.092  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xhdpi-v4/ic_search_category_default.png
08-07 22:37:15.102  30035-30035/ru.furry.furview2 D/AbsListView﹕ Get MotionRecognitionManager
08-07 22:37:15.122  30035-30035/ru.furry.furview2 D/fgsfds﹕ UIL initialization
08-07 22:37:15.132  30035-30035/ru.furry.furview2 D/Activity﹕ performCreate Call secproduct feature valuefalse
08-07 22:37:15.132  30035-30035/ru.furry.furview2 D/Activity﹕ performCreate Call debug elastic valuetrue
08-07 22:37:15.132  30035-30035/ru.furry.furview2 D/fgsfds﹕ Restore proxy setting: none
08-07 22:37:15.147  30035-30059/ru.furry.furview2 D/OpenGLRenderer﹕ Render dirty regions requested: true
08-07 22:37:15.157  30035-30035/ru.furry.furview2 D/Atlas﹕ Validating map...
08-07 22:37:15.182  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
08-07 22:37:15.182  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
08-07 22:37:15.187  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
08-07 22:37:15.187  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
08-07 22:37:15.187  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_000.png
08-07 22:37:15.187  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_001.png
08-07 22:37:15.192  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_002.png
08-07 22:37:15.192  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_003.png
08-07 22:37:15.192  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_004.png
08-07 22:37:15.192  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_005.png
08-07 22:37:15.192  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_006.png
08-07 22:37:15.197  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_007.png
08-07 22:37:15.197  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_008.png
08-07 22:37:15.197  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_010.png
08-07 22:37:15.202  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_011.png
08-07 22:37:15.202  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_012.png
08-07 22:37:15.202  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_013.png
08-07 22:37:15.202  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_014.png
08-07 22:37:15.202  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_on_mtrl_015.png
08-07 22:37:15.207  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_000.png
08-07 22:37:15.207  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_001.png
08-07 22:37:15.207  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_002.png
08-07 22:37:15.207  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_003.png
08-07 22:37:15.212  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_004.png
08-07 22:37:15.212  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_005.png
08-07 22:37:15.212  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_006.png
08-07 22:37:15.212  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_007.png
08-07 22:37:15.212  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_008.png
08-07 22:37:15.217  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_010.png
08-07 22:37:15.217  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_011.png
08-07 22:37:15.217  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_012.png
08-07 22:37:15.222  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_013.png
08-07 22:37:15.222  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_014.png
08-07 22:37:15.222  30035-30035/ru.furry.furview2 V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/btn_radio_to_off_mtrl_015.png
08-07 22:37:15.262  30035-30059/ru.furry.furview2 I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-07 22:37:15.262  30035-30059/ru.furry.furview2 W/OpenGLRenderer﹕ Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
08-07 22:37:15.277  30035-30059/ru.furry.furview2 D/OpenGLRenderer﹕ Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
08-07 22:37:15.277  30035-30059/ru.furry.furview2 D/OpenGLRenderer﹕ Enabling debug mode 0
08-07 22:37:15.282  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:15.287  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:15.287  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:15.287  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:15.557  30035-30035/ru.furry.furview2 I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@36b1ff3e time:210931195
08-07 22:37:24.772  30035-30035/ru.furry.furview2 D/ViewRootImpl﹕ ViewPostImeInputStage ACTION_DOWN
08-07 22:37:24.952  30035-30035/ru.furry.furview2 D/fgsfds﹕ Enabled elements on screen = 29 Ready to block.
08-07 22:37:24.952  30035-30035/ru.furry.furview2 D/fgsfds﹕ storage: /storage/emulated/0/Android/data/ru.furry.furview2/files/storage/emulated/0/Pictures
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Search:
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Clearing image 0
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Clearing image 1
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Clearing image 2
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Clearing image 3
08-07 22:37:24.962  30035-30035/ru.furry.furview2 D/fgsfds﹕ Lock UI! counterTheads after locking =1
08-07 22:37:24.967  30035-30035/ru.furry.furview2 D/Activity﹕ performCreate Call secproduct feature valuefalse
08-07 22:37:24.967  30035-30035/ru.furry.furview2 D/Activity﹕ performCreate Call debug elastic valuetrue
08-07 22:37:24.967  30035-30136/ru.furry.furview2 D/fgsfds﹕ Starting retrieving remote images...
08-07 22:37:24.987  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-07 22:37:24.992  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isShipBuild true
08-07 22:37:24.992  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Thread-102355-398561371: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
08-07 22:37:24.992  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-07 22:37:24.997  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.002  30035-30136/ru.furry.furview2 I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 22:37:25.002  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.002  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.002  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.042  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.042  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.097  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.097  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.107  30035-30035/ru.furry.furview2 I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@289e3f3f time:210940745
08-07 22:37:25.107  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.107  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.117  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-07 22:37:25.117  30035-30136/ru.furry.furview2 I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 22:37:25.162  30035-30059/ru.furry.furview2 D/OpenGLRenderer﹕ endAllStagingAnimators on 0xb4de2e00 (RippleDrawable) with handle 0xa1affdf0
08-07 22:37:25.232  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-07 22:37:25.232  30035-30136/ru.furry.furview2 I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 22:37:25.247  30035-30035/ru.furry.furview2 V/ActivityThread﹕ updateVisibility : ActivityRecord{29662209 token=android.os.BinderProxy@36b1ff3e {ru.furry.furview2/ru.furry.furview2.InitialScreen}} show : false
08-07 22:37:25.262  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.262  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.337  30035-30136/ru.furry.furview2 I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-07 22:37:25.342  30035-30136/ru.furry.furview2 I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 22:37:25.462  30035-30136/ru.furry.furview2 E/furry error﹕ javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xaf537e00: I/O error during system call, Connection reset by peer
            at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:320)
            at com.android.okhttp.Connection.upgradeToTls(Connection.java:1285)
            at com.android.okhttp.Connection.connect(Connection.java:1197)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:295)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:190)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
            at ru.furry.furview2.drivers.e621.DriverE621$ReadingImages.doInBackground(DriverE621.java:170)
            at ru.furry.furview2.drivers.e621.DriverE621$ReadingImages.doInBackground(DriverE621.java:148)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-07 22:37:25.467  30035-30136/ru.furry.furview2 E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #3
    Process: ru.furry.furview2, PID: 30035
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'org.w3c.dom.Element org.w3c.dom.Document.getDocumentElement()' on a null object reference
            at ru.furry.furview2.drivers.e621.DriverE621$ReadingImages.doInBackground(DriverE621.java:175)
            at ru.furry.furview2.drivers.e621.DriverE621$ReadingImages.doInBackground(DriverE621.java:148)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-07 22:37:25.587  30035-30035/ru.furry.furview2 D/fgsfds﹕ Restore proxy setting: none
08-07 22:37:25.612  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.617  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.617  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.617  30035-30059/ru.furry.furview2 E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
08-07 22:37:25.697  30035-30035/ru.furry.furview2 I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@36b1ff3e time:210941335
08-07 22:37:25.822  30035-30035/ru.furry.furview2 D/fgsfds﹕ Clearing cache.
08-07 22:37:31.472  30035-30136/ru.furry.furview2 I/Process﹕ Sending signal. PID: 30035 SIG: 9
```

**Comment by Zey-Uzh** [comment]
Может падать в следующих ситуациях:
- нет подключения к инету (https://github.com/IngvarJackal/FurView2/issues/83)
- в России не включашь прокси (https://github.com/IngvarJackal/FurView2/issues/83)
- выбранное прокси лежит (https://github.com/IngvarJackal/FurView2/issues/83)

Необходимо сделать обработку данных ситуация.

**Comment by connertech** [comment]
Не включил прокси (забыл, что для меня он вообще-то обязателен).
